// Exports one user's full data tree (shift templates, responsibility templates,
// staff groups, staff, preferences, rosters) as a standalone SQL file, for
// manually seeding a demo account in another database (e.g. production).
//
// Usage: node scripts/exportUserDataToSql.mjs <source-email> [--as <demo-email>] [--out <path>]
//   --as   remap the exported account's email (default: keep the source email)
//   --out  output file path (default: demo-seed.sql in the current directory)

import { PrismaClient } from '@prisma/client';
import { writeFileSync } from 'node:fs';

const prisma = new PrismaClient();

function parseArgs(argv) {
  const [sourceEmail, ...rest] = argv;
  let asEmail = sourceEmail;
  let out = 'demo-seed.sql';
  for (let i = 0; i < rest.length; i++) {
    if (rest[i] === '--as') asEmail = rest[++i];
    else if (rest[i] === '--out') out = rest[++i];
  }
  return { sourceEmail, asEmail, out };
}

function sqlString(value) {
  return `'${String(value).replace(/'/g, "''")}'`;
}

function sqlValue(value) {
  if (value === null || value === undefined) return 'NULL';
  if (typeof value === 'number') return String(value);
  if (typeof value === 'boolean') return value ? 'TRUE' : 'FALSE';
  if (value instanceof Date) return sqlString(value.toISOString());
  return sqlString(String(value));
}

function sqlTextArray(values) {
  if (!values || values.length === 0) return "'{}'::text[]";
  return `ARRAY[${values.map((v) => sqlString(v)).join(', ')}]::text[]`;
}

function sqlJson(value) {
  return `${sqlString(JSON.stringify(value ?? null))}::jsonb`;
}

function insert(table, columns, values, conflictColumns) {
  const cols = columns.map((c) => `"${c}"`).join(', ');
  const vals = values.join(', ');
  const conflict = conflictColumns ? ` ON CONFLICT (${conflictColumns.map((c) => `"${c}"`).join(', ')}) DO NOTHING` : '';
  return `INSERT INTO "${table}" (${cols}) VALUES (${vals})${conflict};`;
}

async function main() {
  const { sourceEmail, asEmail, out } = parseArgs(process.argv.slice(2));
  if (!sourceEmail) {
    console.error('Usage: node scripts/exportUserDataToSql.mjs <source-email> [--as <demo-email>] [--out <path>]');
    process.exit(1);
  }

  const user = await prisma.user.findUnique({ where: { email: sourceEmail } });
  if (!user) {
    console.error(`No user found with email ${sourceEmail}`);
    process.exit(1);
  }

  const [shiftTemplates, responsibilityTemplates, staffGroups, staff, groupMembers, rosters] = await Promise.all([
    prisma.shiftTemplate.findMany({ where: { userId: user.id } }),
    prisma.responsibilityTemplate.findMany({ where: { userId: user.id } }),
    prisma.staffGroup.findMany({ where: { userId: user.id } }),
    prisma.staff.findMany({ where: { userId: user.id }, include: { preference: true } }),
    prisma.groupMember.findMany({ where: { group: { userId: user.id } } }),
    prisma.roster.findMany({ where: { userId: user.id }, include: { rosterShifts: { include: { assignments: true } } } }),
  ]);

  const lines = [];
  lines.push('-- Generated by scripts/exportUserDataToSql.mjs');
  lines.push(`-- Source account: ${sourceEmail}`);
  lines.push(`-- Exported as: ${asEmail}`);
  lines.push('BEGIN;');
  lines.push('');

  lines.push('-- User');
  lines.push(
    insert(
      'User',
      ['id', 'email', 'passwordHash', 'googleId', 'createdAt'],
      [sqlValue(user.id), sqlValue(asEmail), 'NULL', 'NULL', sqlValue(user.createdAt)],
      ['email']
    )
  );
  lines.push('');

  if (shiftTemplates.length > 0) {
    lines.push('-- ShiftTemplate');
    for (const t of shiftTemplates) {
      lines.push(
        insert(
          'ShiftTemplate',
          ['id', 'userId', 'name', 'startTime', 'endTime', 'createdAt'],
          [sqlValue(t.id), sqlValue(user.id), sqlValue(t.name), sqlValue(t.startTime), sqlValue(t.endTime), sqlValue(t.createdAt)],
          ['id']
        )
      );
    }
    lines.push('');
  }

  if (responsibilityTemplates.length > 0) {
    lines.push('-- ResponsibilityTemplate');
    for (const r of responsibilityTemplates) {
      lines.push(
        insert(
          'ResponsibilityTemplate',
          ['id', 'userId', 'name', 'createdAt'],
          [sqlValue(r.id), sqlValue(user.id), sqlValue(r.name), sqlValue(r.createdAt)],
          ['id']
        )
      );
    }
    lines.push('');
  }

  if (staffGroups.length > 0) {
    lines.push('-- StaffGroup');
    for (const g of staffGroups) {
      lines.push(
        insert(
          'StaffGroup',
          ['id', 'userId', 'name', 'createdAt'],
          [sqlValue(g.id), sqlValue(user.id), sqlValue(g.name), sqlValue(g.createdAt)],
          ['id']
        )
      );
    }
    lines.push('');
  }

  if (staff.length > 0) {
    lines.push('-- Staff');
    for (const s of staff) {
      lines.push(
        insert(
          'Staff',
          ['id', 'userId', 'name', 'email', 'responsibilityIds', 'createdAt'],
          [sqlValue(s.id), sqlValue(user.id), sqlValue(s.name), sqlValue(s.email), sqlTextArray(s.responsibilityIds), sqlValue(s.createdAt)],
          ['id']
        )
      );
    }
    lines.push('');

    const preferences = staff.map((s) => s.preference).filter(Boolean);
    if (preferences.length > 0) {
      lines.push('-- Preference');
      for (const p of preferences) {
        lines.push(
          insert(
            'Preference',
            ['id', 'staffId', 'preferredShifts', 'unavailableShifts', 'unavailableDateRanges', 'minHours', 'maxHours', 'hoursPeriod', 'hoursUnit'],
            [
              sqlValue(p.id),
              sqlValue(p.staffId),
              sqlJson(p.preferredShifts),
              sqlJson(p.unavailableShifts),
              sqlJson(p.unavailableDateRanges),
              sqlValue(p.minHours),
              sqlValue(p.maxHours),
              sqlValue(p.hoursPeriod),
              sqlValue(p.hoursUnit),
            ],
            ['id']
          )
        );
      }
      lines.push('');
    }
  }

  if (groupMembers.length > 0) {
    lines.push('-- GroupMember');
    for (const m of groupMembers) {
      lines.push(insert('GroupMember', ['groupId', 'staffId'], [sqlValue(m.groupId), sqlValue(m.staffId)], ['groupId', 'staffId']));
    }
    lines.push('');
  }

  if (rosters.length > 0) {
    lines.push('-- Roster');
    for (const r of rosters) {
      lines.push(
        insert(
          'Roster',
          ['id', 'userId', 'name', 'dateRangeStart', 'dateRangeEnd', 'groupId', 'status', 'hoursPerShift', 'createdAt'],
          [
            sqlValue(r.id),
            sqlValue(user.id),
            sqlValue(r.name),
            sqlValue(r.dateRangeStart),
            sqlValue(r.dateRangeEnd),
            sqlValue(r.groupId),
            sqlValue(r.status),
            sqlValue(r.hoursPerShift),
            sqlValue(r.createdAt),
          ],
          ['id']
        )
      );
    }
    lines.push('');

    const rosterShifts = rosters.flatMap((r) => r.rosterShifts);
    if (rosterShifts.length > 0) {
      lines.push('-- RosterShift');
      for (const rs of rosterShifts) {
        lines.push(
          insert(
            'RosterShift',
            ['id', 'rosterId', 'shiftTemplateId', 'date', 'headcount', 'responsibilityId'],
            [sqlValue(rs.id), sqlValue(rs.rosterId), sqlValue(rs.shiftTemplateId), sqlValue(rs.date), sqlValue(rs.headcount), sqlValue(rs.responsibilityId)],
            ['id']
          )
        );
      }
      lines.push('');
    }

    const assignments = rosterShifts.flatMap((rs) => rs.assignments);
    if (assignments.length > 0) {
      lines.push('-- Assignment');
      for (const a of assignments) {
        lines.push(
          insert(
            'Assignment',
            ['id', 'rosterShiftId', 'staffId', 'unfilledTag'],
            [sqlValue(a.id), sqlValue(a.rosterShiftId), sqlValue(a.staffId), sqlValue(a.unfilledTag)],
            ['id']
          )
        );
      }
      lines.push('');
    }
  }

  lines.push('COMMIT;');

  writeFileSync(out, lines.join('\n') + '\n', 'utf8');
  console.log(`Wrote ${out} — 1 user, ${shiftTemplates.length} shift templates, ${responsibilityTemplates.length} responsibility templates, ${staffGroups.length} groups, ${staff.length} staff, ${rosters.length} rosters.`);
}

main()
  .catch((err) => {
    console.error(err);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
